Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,6 +36,10 @@ jobs:
               rm -r ci-pipeline-trial;
               git clone -b dev_Chirag https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/chiragbheemaiah/Integrating-Headless-Gazebo-into-GitHub-Actions.git;
               cd Integrating-Headless-Gazebo-into-GitHub-Actions/Turtlebot3_ws;
+              if [ ! -f src/infra/worlds/2x_world_only.model ]; then
+              echo "Error: model file does not exist."
+              exit 1
+              fi
               cp src/infra/worlds/2x_world_only.model /opt/ros/humble/share/nav2_bringup/worlds/world_only.model;
               colcon build --symlink-install;
               source install/setup.bash;
